name: Run tests on demand

on:
  workflow_dispatch

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Download Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run:
        pytest