name: Run tests on demand

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose test scope
        required: true
        default: All tests
        type: choice
        options:
          - All tests
          - API tests
          - UI tests

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Download Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all tests
      if: "github.event.inputs.deployment_target == 'All tests'"
      run:
        pytest

    - name: Run API tests
      if: "github.event.inputs.deployment_target == 'API tests'"
      run:
        pytest -m api

    - name: Run UI tests
      if: "github.event.inputs.deployment_target == 'UI tests'"
      run:
        pytest -m ui

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: test_run_data/